export enum Building {
    Assembler = "Assembler",
    Blender = "Blender",
    Constructor = "Constructor",
    CraftBench = "Craft Bench",
    EquipmentWorkshop = "Equipment Workshop",
    Foundry = "Foundry",
    Manufacturer = "Manufacturer",
    MinerMk1 = "Miner Mk.1",
    MinerMk2 = "Miner Mk.2",
    MinerMk3 = "Miner Mk.3",
    NuclearPowerPlant = "Nuclear Power Plant",
    OilExtractor = "Oil Extractor",
    Packager = "Packager",
    ParticleAccelerator = "Particle Accelerator",
    Refinery = "Refinery",
    ResourceWellPressurizer = "Resource Well Pressurizer",
    Smelter = "Smelter",
    WaterExtractor = "Water Extractor"
}